using System.Collections.Generic;

namespace Infragistics.Samples
{
    /// <summary> Defines electricity generated at given year </summary>
    public class EnergyRenewableInfo
    {
        public string Year { get; set; }
        public int Europe { get; set; }
        public int China { get; set; }
        public int USA { get; set; }
    }

    /// <summary> Defines renewable electricity generated by multiple countries </summary>
    public class EnergyRenewableData : List<EnergyRenewableInfo>
    {
        public EnergyRenewableData()
        {
            Add(new EnergyRenewableInfo { Year = "2009", Europe = 31, USA = 19, China = 21 });
            Add(new EnergyRenewableInfo { Year = "2010", Europe = 43, USA = 24, China = 26 });
            Add(new EnergyRenewableInfo { Year = "2011", Europe = 66, USA = 28, China = 29 });
            Add(new EnergyRenewableInfo { Year = "2012", Europe = 69, USA = 26, China = 32 });
            Add(new EnergyRenewableInfo { Year = "2013", Europe = 58, USA = 38, China = 47 });
            Add(new EnergyRenewableInfo { Year = "2014", Europe = 40, USA = 31, China = 46 });
            Add(new EnergyRenewableInfo { Year = "2015", Europe = 78, USA = 19, China = 50 });
            Add(new EnergyRenewableInfo { Year = "2016", Europe = 13, USA = 52, China = 90 });
            Add(new EnergyRenewableInfo { Year = "2017", Europe = 78, USA = 50, China = 132 });
            Add(new EnergyRenewableInfo { Year = "2018", Europe = 40, USA = 34, China = 134 });
            Add(new EnergyRenewableInfo { Year = "2019", Europe = 80, USA = 38, China = 96 });
        }
    }

}