parameters:
  - name: igVersion
  - name: igNuGetFeedUrl
  - name: projectToBuild
  - name: isVerbose
    default: false

steps:
  - task: NodeTool@0
    displayName: 'Install Node'
    inputs:
      versionSource: 'spec'
      versionSpec: '16.x'

  - task: Npm@1
    displayName: 'npm ci'
    inputs:
      command: custom
      workingDir: '$(Build.SourcesDirectory)\browser\IgBlazorSamples.Gulp'
      verbose: ${{ parameters.isVerbose }}
      customCommand: ci

  
  - task: CmdLine@2
    displayName: 'npx gulp copySamplesTo${{ parameters.projectToBuild }}'
    inputs:
      script: 'npx gulp copySamplesTo${{ parameters.projectToBuild }}'
      workingDirectory:  '$(Build.SourcesDirectory)\browser\IgBlazorSamples.Gulp'
      failOnStderr: true

  - task: UseDotNet@2
    displayName: 'Install dotnet if not already present'
    inputs:
      packageType: 'sdk'
      version: '8.0.100' # we are currently building a 8.0 app. TODO: Try upgrading to 8.x in the future
      performMultiLevelLookup: true

  - task: PowerShell@2
    displayName: 'Generate NuGet.config for IG ProGet NuGet feed'
    inputs:
      targetType: 'inline'
      script: |
        dotnet new nugetconfig --force
        # The name of the source doesn't currently matter as the credentials are attached thanks to URL matching - according to MS docs
        dotnet nuget add source ${{ parameters.igNuGetFeedUrl }} --name "IG ProGet NuGet" 

        $xml = [XML](Get-Content '.\IgBlazorSamples.${{ parameters.projectToBuild }}.csproj');

        $nodes = $xml.SelectNodes("//PackageReference[starts-with(@Include,'IgniteUI')]") | 
          ForEach-Object { 
              $_.SetAttribute("Include",$_.Include.Replace(".Trial",""));
              $_.SetAttribute("Version", "${{ parameters.igVersion }}");
              Write-Host $_.Version
          }
        $xml.Save('.\IgBlazorSamples.${{ parameters.projectToBuild }}.csproj')
      failOnStderr: true
      showWarnings: true
      workingDirectory: '$(Build.SourcesDirectory)\browser\IgBlazorSamples.${{ parameters.projectToBuild }}'

  - task: DotNetCoreCLI@2
    displayName: 'dotnet restore'
    inputs:
      command: 'restore'
      projects: '$(Build.SourcesDirectory)\browser\IgBlazorSamples.${{ parameters.projectToBuild }}'
      restoreArguments: '--ignore-failed-sources --no-cache --force'
      feedsToUse: 'config'
      nugetConfigPath: '$(Build.SourcesDirectory)\browser\IgBlazorSamples.${{ parameters.projectToBuild }}\NuGet.Config'
      externalFeedCredentials: 'IGProGetIgniteUINuGet'
      verbosityRestore: 'Diagnostic'


  - task: DeleteFiles@1
    displayName: 'Delete NuGet.config file - used only at build time'
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)\browser\IgBlazorSamples.${{ parameters.projectToBuild }}\'
      Contents: '**/NuGet.config'

  - task: CmdLine@2
    # Using a CmldLine call for this opeation, because I couldn't get it to work as expected with the DotNetCoreCLI task
    displayName: 'dotnet publish'
    inputs:
      # Skip the restore process as it is already done. Got an error when I tried skipping the build process (which is already done as well) 
      script: 'dotnet publish --no-restore -c release -o $(Build.SourcesDirectory)\browser\IgBlazorSamples.${{ parameters.projectToBuild }}\publish'
      workingDirectory:  '$(Build.SourcesDirectory)\browser\IgBlazorSamples.${{ parameters.projectToBuild }}'

  - task: ArchiveFiles@2
    displayName: 'Package samples browser'
    inputs:
      verbose: ${{ parameters.isVerbose }}
      rootFolderOrFile: '$(Build.SourcesDirectory)/browser/IgBlazorSamples.${{ parameters.projectToBuild }}/publish'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/BlazorSamples${{ parameters.projectToBuild }}.zip'
      replaceExistingArchive: true

  - task: PublishPipelineArtifact@1
    displayName: 'Publish pipeline artifact'
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)/BlazorSamples${{ parameters.projectToBuild }}.zip'
      artifact: 'BlazorSamples${{ parameters.projectToBuild }}'

  # - ${{ if eq(parameters.shouldCleanPostExectuion, true) }}:
  #   - task: PostBuildCleanup@4
