trigger:
  branches:
    include:
    - vnext
    - master
    - azure-pipelines
  paths:
    exclude:
    - browser/IgBlazorSamples.Client/

# This pipeline is meant to build specific branches for deployment. It's not meant to be a part of PR validation.
pr: none

parameters:
- name: isVerbose
  displayName: 'Get verbose output from steps - where configurable'
  type: boolean
  default: false
- name: shouldCleanPostExectuion
  displayName: 'Clean all pipeline dirs after the pipeline finishes?'
  type: boolean
  default: true

name: $(BuildDefinitionName)_$(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.r)

stages:
- stage: Build
  pool:
    name: BuildAgentOnPrem
    demands: npm
  jobs:
  - job: BuildSamples
    steps:
      # This specific checkout is necessary for custom logic in the gulp processes. Once we retire them, this custom behavior can be deleted.
      - checkout: 'self'
        path: $(Build.Repository.Name)

      - template: templates/build-steps-template.yml
        parameters:
          igVersion: '24.2.111'
          igNuGetFeedUrl: $(IG_Nuget_Feed_URL)
          projectToBuild: Server
          isVerbose: ${{ parameters.isVerbose }}
          shouldCleanPostExectuion: ${{ parameters.shouldCleanPostExectuion }}
          username: $(IG_Nuget_Feed_Username)
          password: $(IG_Nuget_Feed_Password)
