trigger:
  branches:
    include:
    - vnext
    - master
    - azure-pipelines
  paths:
    exclude:
    - browser/IgBlazorSamples.Client/
pr:
  branches:
    exclude:
    - '*'  # must quote since "*" is a YAML reserved character; we want a string

parameters:
- name: isVerbose
  displayName: 'Get verbose output from steps - where configurable'
  type: boolean
  default: false

name: $(BuildDefinitionName)_$(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.r)

stages:
- stage: Build
  pool:
    name: BuildAgentOnPrem
    demands: npm
  jobs:
  - job: BuildSamples
    steps:
      # This specific checkout is necessary for custom logic in the gulp processes. Once we retire them, this custom behavior can be deleted.
      - checkout: 'self' 
        path: $(Build.Repository.Name)

      - template: templates/build-steps-template.yml
        parameters:
          igVersion: '22.2.60'
          igNuGetFeedUrl: $(IG_Nuget_Feed_URL)
          projectToBuild: Server
          isVerbose: ${{ parameters.isVerbose }}
